import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

const EISCThirdFloor = (props) => {
    const { nodes, materials } = useGLTF("/assets/models/EISCThirdFloor.glb");
    return (
        <group {...props} dispose={null}>
            <group>
                <RigidBody type="fixed" colliders="trimesh" friction={0.7} restitution={0} >
                    <mesh geometry={nodes.ThirdFloor.geometry} material={materials.floor} />
                </RigidBody>
                <RigidBody type="fixed" colliders="trimesh" name="EISCBody" friction={0.7} restitution={0} >
                    <group>
                        <mesh
                            geometry={nodes.StructureThirdFloor_1.geometry}
                            material={materials.wall}
                        />
                        <mesh
                            geometry={nodes.StructureThirdFloor_2.geometry}
                            material={materials.glass}
                        />
                        <mesh
                            geometry={nodes.StructureThirdFloor_3.geometry}
                            material={materials.rack}
                        />
                        <mesh
                            geometry={nodes.StructureThirdFloor_4.geometry}
                            material={materials.brown}
                        />
                        <mesh
                            geometry={nodes.StructureThirdFloor_5.geometry}
                            material={materials.alu}
                        />
                        <mesh
                            geometry={nodes.StructureThirdFloor_6.geometry}
                            material={materials.camaleonWindow}
                        />
                        <mesh
                            geometry={nodes.StructureThirdFloor_7.geometry}
                            material={materials.camaleonDoor}
                        />
                    </group>
                </RigidBody>
                <mesh
                    geometry={nodes.TopThirdFloor.geometry}
                    material={materials.wall}
                />
                <RigidBody type="fixed" name="EISCBody" friction={0.7} restitution={0} >
                    <group>
                        <mesh
                            geometry={nodes.ComputersGoticBack_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersGoticBack_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersGoticFront_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersGoticFront_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksGoticBack_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksGoticBack_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksGoticFront_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksGoticFront_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsGoticFront_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsGoticFront_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsGoticBack_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsGoticBack_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersAvispaBack_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersAvispaBack_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersAvispaFront_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersAvispaFront_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksAvispaBack_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksAvispaBack_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksAvispaFront_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksAvispaFront_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsAvispaFront_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsAvispaFront_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsAvispaBack_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsAvispaBack_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersBioinformaticaBack_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersBioinformaticaBack_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersBioinformaticaFront_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersBioinformaticaFront_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksBioinformaticaBack_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksBioinformaticaBack_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksBioinformaticaFront_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksBioinformaticaFront_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsBioinformaticaFront_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsBioinformaticaFront_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsBioinformaticaBack_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsBioinformaticaBack_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersCamaleonBack_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersCamaleonBack_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersCamaleonFront_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersCamaleonFront_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksCamaleonBack_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksCamaleonBack_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksCamaleonFront_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksCamaleonFront_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsCamaleonFront_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsCamaleonFront_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsCamaleonBack_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsCamaleonBack_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersCedesoftBack_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersCedesoftBack_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersCedesoftFront_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersCedesoftFront_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksCedesoftBack_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksCedesoftBack_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksCedesoftFront_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksCedesoftFront_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsCedesoftFront_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsCedesoftFront_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsCedesoftBack_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsCedesoftBack_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <mesh geometry={nodes.DeskComite.geometry} material={materials.desk} />
                    <group>
                        <mesh
                            geometry={nodes.ChairsComite_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsComite_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersEvaBack_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersEvaBack_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersEvaFront_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersEvaFront_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksEvaBack_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksEvaBack_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksEvaFront_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksEvaFront_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsEvaFront_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsEvaFront_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsEvaBack_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsEvaBack_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersKDDBack_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersKDDBack_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersKDDFront_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersKDDFront_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksKDDBack_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksKDDBack_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksKDDFront_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksKDDFront_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsKDDFront_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsKDDFront_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsKDDBack_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsKDDBack_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersMulticedesBack_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersMulticedesBack_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersMulticedesFront_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersMulticedesFront_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksMulticedesBack_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksMulticedesBack_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksMulticedesFront_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksMulticedesFront_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsMulticedesFront_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsMulticedesFront_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsMulticedesBack_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsMulticedesBack_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersMultimediaBack_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersMultimediaBack_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersMultimediaFront_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersMultimediaFront_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksMultimediaBack_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksMultimediaBack_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksMultimediaFront_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksMultimediaFront_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsMultimediaFront_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsMultimediaFront_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsMultimediaBack_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsMultimediaBack_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersRedesBack_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersRedesBack_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ComputersRedesFront_1.geometry}
                            material={materials.metalBlackComputer}
                        />
                        <mesh
                            geometry={nodes.ComputersRedesFront_2.geometry}
                            material={materials.windowComputer}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksRedesBack_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksRedesBack_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.DesksRedesFront_1.geometry}
                            material={materials.desk}
                        />
                        <mesh
                            geometry={nodes.DesksRedesFront_2.geometry}
                            material={materials.deskPizarra}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsRedesFront_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsRedesFront_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                    <group>
                        <mesh
                            geometry={nodes.ChairsRedesBack_1.geometry}
                            material={materials.MaterialChairBlack}
                        />
                        <mesh
                            geometry={nodes.ChairsRedesBack_2.geometry}
                            material={materials.MaterialChairRed}
                        />
                    </group>
                </RigidBody>
            </group>
        </group>
    );
}

export default EISCThirdFloor;
useGLTF.preload("/assets/models/EISCThirdFloor.glb");