import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

/**
 * Component representing the third floor of the Escuela de Ingeniería de Sistemas y Computación (EISC) building.
 * @param {Object} props - The props passed to the component.
 * @returns {JSX.Element} The JSX.Element containing the third floor model.
 */
export default function EISCThirdFloor(props) {
  const { nodes, materials } = useGLTF("/assets/models/EISCThirdFloor.glb");

  return (
    <group {...props} dispose={null}>
      <group>
        <RigidBody type="fixed" colliders="trimesh">
          <mesh
            geometry={nodes.ThirdFloor.geometry}
            material={materials.floor}
          />
        </RigidBody>
        <RigidBody type="fixed" colliders="trimesh" restitution={0}>
          <group>
            <mesh
              geometry={nodes.StructureThirdFloor_1.geometry}
              material={materials.wall}
            />
            <mesh
              geometry={nodes.StructureThirdFloor_2.geometry}
              material={materials.glass}
            />
            <mesh
              geometry={nodes.StructureThirdFloor_3.geometry}
              material={materials.rack}
            />
            <mesh
              geometry={nodes.StructureThirdFloor_4.geometry}
              material={materials.brown}
            />
            <mesh
              geometry={nodes.StructureThirdFloor_5.geometry}
              material={materials.alu}
            />
            <mesh
              geometry={nodes.StructureThirdFloor_6.geometry}
              material={materials.camaleonWindow}
            />
            <mesh
              geometry={nodes.StructureThirdFloor_7.geometry}
              material={materials.camaleonDoor}
            />
          </group>
        </RigidBody>
        <RigidBody type="fixed">
          <group>
            <mesh
              geometry={nodes.DesksGediBack_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksGediBack_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.DesksGediFront_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksGediFront_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsGediFront_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsGediFront_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsGediBack_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsGediBack_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.DesksAvispaBack_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksAvispaBack_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.DesksAvispaFront_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksAvispaFront_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsAvispaFront_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsAvispaFront_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsAvispaBack_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsAvispaBack_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.DesksBioinformaticaBack_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksBioinformaticaBack_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.DesksBioinformaticaFront_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksBioinformaticaFront_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsBioinformaticaFront_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsBioinformaticaFront_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsBioinformaticaBack_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsBioinformaticaBack_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.DesksCamaleonBack_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksCamaleonBack_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.DesksCamaleonFront_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksCamaleonFront_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsCamaleonFront_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsCamaleonFront_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsCamaleonBack_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsCamaleonBack_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.DesksCedesoftBack_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksCedesoftBack_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.DesksCedesoftFront_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksCedesoftFront_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsCedesoftFront_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsCedesoftFront_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsCedesoftBack_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsCedesoftBack_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
          <mesh
            geometry={nodes.DeskComite.geometry}
            material={materials.desk}
          />
          <group>
            <mesh
              geometry={nodes.ChairsComite_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsComite_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.DesksEvaBack_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksEvaBack_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.DesksEvaFront_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksEvaFront_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsEvaFront_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsEvaFront_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsEvaBack_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsEvaBack_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.DesksKDDBack_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksKDDBack_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.DesksKDDFront_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksKDDFront_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsKDDFront_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsKDDFront_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsKDDBack_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsKDDBack_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>

          <group>
            <mesh
              geometry={nodes.DesksMulticedesBack_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksMulticedesBack_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.DesksMulticedesFront_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksMulticedesFront_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsMulticedesFront_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsMulticedesFront_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsMulticedesBack_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsMulticedesBack_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>

          <group>
            <mesh
              geometry={nodes.DesksMultimediaBack_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksMultimediaBack_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.DesksMultimediaFront_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksMultimediaFront_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsMultimediaFront_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsMultimediaFront_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsMultimediaBack_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsMultimediaBack_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>

          <group>
            <mesh
              geometry={nodes.DesksRedesBack_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksRedesBack_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.DesksRedesFront_1.geometry}
              material={materials.desk}
            />
            <mesh
              geometry={nodes.DesksRedesFront_2.geometry}
              material={materials.deskPizarra}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsRedesFront_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsRedesFront_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
          <group>
            <mesh
              geometry={nodes.ChairsRedesBack_1.geometry}
              material={materials.MaterialChairBlack}
            />
            <mesh
              geometry={nodes.ChairsRedesBack_2.geometry}
              material={materials.MaterialChairRed}
            />
          </group>
        </RigidBody>
        <group>
          <mesh
            geometry={nodes.WhiteboardAvispa_1.geometry}
            material={materials.mark}
          />
          <mesh
            geometry={nodes.WhiteboardAvispa_2.geometry}
            material={materials.board}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.WhiteboardBioinformatica_1.geometry}
            material={materials.mark}
          />
          <mesh
            geometry={nodes.WhiteboardBioinformatica_2.geometry}
            material={materials.board}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.WhiteboardCamaleon_1.geometry}
            material={materials.mark}
          />
          <mesh
            geometry={nodes.WhiteboardCamaleon_2.geometry}
            material={materials.board}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.WhiteboardCedesfot_1.geometry}
            material={materials.mark}
          />
          <mesh
            geometry={nodes.WhiteboardCedesfot_2.geometry}
            material={materials.board}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.WhiteboardEva_1.geometry}
            material={materials.mark}
          />
          <mesh
            geometry={nodes.WhiteboardEva_2.geometry}
            material={materials.board}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.WhiteboardKDD_1.geometry}
            material={materials.mark}
          />
          <mesh
            geometry={nodes.WhiteboardKDD_2.geometry}
            material={materials.board}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.WhiteboardMulticedes_1.geometry}
            material={materials.mark}
          />
          <mesh
            geometry={nodes.WhiteboardMulticedes_2.geometry}
            material={materials.board}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.WhiteboardGedi_1.geometry}
            material={materials.mark}
          />
          <mesh
            geometry={nodes.WhiteboardGedi_2.geometry}
            material={materials.board}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.WhiteboardMultimedia_1.geometry}
            material={materials.mark}
          />
          <mesh
            geometry={nodes.WhiteboardMultimedia_2.geometry}
            material={materials.board}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.WhiteboardRedes_1.geometry}
            material={materials.mark}
          />
          <mesh
            geometry={nodes.WhiteboardRedes_2.geometry}
            material={materials.board}
          />
        </group>
        <mesh
          geometry={nodes.TopThirdFloor.geometry}
          material={materials.wall}
        />
        <group>
          <mesh
            geometry={nodes.ComputersAvispaBack_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersAvispaBack_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersAvispaFront_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersAvispaFront_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersBioinformaticaBack_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersBioinformaticaBack_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersBioinformaticaFront_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersBioinformaticaFront_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersCamaleonBack_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersCamaleonBack_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersCamaleonFront_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersCamaleonFront_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersCedesoftBack_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersCedesoftBack_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersCedesoftFront_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersCedesoftFront_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersEvaBack_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersEvaBack_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersEvaFront_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersEvaFront_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersKDDBack_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersKDDBack_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersKDDFront_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersKDDFront_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersMulticedesBack_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersMulticedesBack_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersMulticedesFront_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersMulticedesFront_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersMultimediaBack_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersMultimediaBack_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersMultimediaFront_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersMultimediaFront_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersRedesBack_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersRedesBack_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersRedesFront_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersRedesFront_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersGediBack_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersGediBack_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.ComputersGediFront_1.geometry}
            material={materials.metalBlackComputer}
          />
          <mesh
            geometry={nodes.ComputersGediFront_2.geometry}
            material={materials.windowComputer}
          />
        </group>
        <mesh
          geometry={nodes.SignGedi.geometry}
          material={materials.SignGedi}
        />
        <mesh
          geometry={nodes.SignLenguajes.geometry}
          material={materials.SignLenguajes}
        />
        <mesh
          geometry={nodes.SignBioinformatic.geometry}
          material={materials.SignBioinformatic}
        />
        <mesh
          geometry={nodes.SignCamaleon.geometry}
          material={materials.SignCamaleon}
        />
        <mesh
          geometry={nodes.SignCedesoft.geometry}
          material={materials.SignCedesoft}
        />
        <mesh
          geometry={nodes.SignRoomComite.geometry}
          material={materials.SignRoomComite}
        />
        <mesh geometry={nodes.SignEva.geometry} material={materials.SignEva} />
        <mesh geometry={nodes.SignKDD.geometry} material={materials.SignKDD} />
        <mesh
          geometry={nodes.SignMulticedes.geometry}
          material={materials.SignMulticedes}
        />
        <mesh
          geometry={nodes.SignMultimedia.geometry}
          material={materials.SignMultimedia}
        />
        <mesh
          geometry={nodes.SignRedes.geometry}
          material={materials.SignRedes}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/EISCThirdFloor.glb");
