import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

const EISCSecondFloor = (props) => {
  const { nodes, materials } = useGLTF("/models/EISCSecondFloor.glb");

  return (
    <group {...props} dispose={null}>
      <RigidBody
        colliders="trimesh"
        type="fixed"
      >
        {/* SctructureSecondFloor */}
        <group>
          <mesh
            geometry={nodes.StructureSecondFloor_1.geometry}
            material={materials.wall}
          />
          <mesh
            geometry={nodes.StructureSecondFloor_2.geometry}
            material={materials.rack}
          />
          <mesh
            geometry={nodes.StructureSecondFloor_3.geometry}
            material={materials.alu}
          />
          <mesh
            geometry={nodes.StructureSecondFloor_4.geometry}
            material={materials.glass}
          />
          <mesh
            geometry={nodes.StructureSecondFloor_5.geometry}
            material={materials.brown}
          />
        </group>
        {/* Doors */}
        <group>
          <mesh
            geometry={nodes.Door2002_1.geometry}
            material={materials.wall}
          />
          <mesh
            geometry={nodes.Door2002_2.geometry}
            material={materials.rack}
          />
          <mesh geometry={nodes.Door2002_3.geometry} material={materials.alu} />
          <mesh
            geometry={nodes.Door2002_4.geometry}
            material={materials.glass}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.Door2008_1.geometry}
            material={materials.wall}
          />
          <mesh
            geometry={nodes.Door2008_2.geometry}
            material={materials.rack}
          />
          <mesh geometry={nodes.Door2008_3.geometry} material={materials.alu} />
          <mesh
            geometry={nodes.Door2008_4.geometry}
            material={materials.glass}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.DoorCenesis_1.geometry}
            material={materials.wall}
          />
          <mesh
            geometry={nodes.DoorCenesis_2.geometry}
            material={materials.rack}
          />
          <mesh
            geometry={nodes.DoorCenesis_3.geometry}
            material={materials.alu}
          />
          <mesh
            geometry={nodes.DoorCenesis_4.geometry}
            material={materials.glass}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.DoorComputerRoom1R_1.geometry}
            material={materials.wall}
          />
          <mesh
            geometry={nodes.DoorComputerRoom1R_2.geometry}
            material={materials.rack}
          />
          <mesh
            geometry={nodes.DoorComputerRoom1R_3.geometry}
            material={materials.alu}
          />
          <mesh
            geometry={nodes.DoorComputerRoom1R_4.geometry}
            material={materials.glass}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.DoorComputerRoom1L_1.geometry}
            material={materials.wall}
          />
          <mesh
            geometry={nodes.DoorComputerRoom1L_2.geometry}
            material={materials.rack}
          />
          <mesh
            geometry={nodes.DoorComputerRoom1L_3.geometry}
            material={materials.alu}
          />
          <mesh
            geometry={nodes.DoorComputerRoom1L_4.geometry}
            material={materials.glass}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.DoorComputerRoom2R_1.geometry}
            material={materials.wall}
          />
          <mesh
            geometry={nodes.DoorComputerRoom2R_2.geometry}
            material={materials.rack}
          />
          <mesh
            geometry={nodes.DoorComputerRoom2R_3.geometry}
            material={materials.alu}
          />
          <mesh
            geometry={nodes.DoorComputerRoom2R_4.geometry}
            material={materials.glass}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.DoorComputerRoom2L_1.geometry}
            material={materials.wall}
          />
          <mesh
            geometry={nodes.DoorComputerRoom2L_2.geometry}
            material={materials.rack}
          />
          <mesh
            geometry={nodes.DoorComputerRoom2L_3.geometry}
            material={materials.alu}
          />
          <mesh
            geometry={nodes.DoorComputerRoom2L_4.geometry}
            material={materials.glass}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.DoorComputerRoom4_1.geometry}
            material={materials.wall}
          />
          <mesh
            geometry={nodes.DoorComputerRoom4_2.geometry}
            material={materials.rack}
          />
          <mesh
            geometry={nodes.DoorComputerRoom4_3.geometry}
            material={materials.alu}
          />
          <mesh
            geometry={nodes.DoorComputerRoom4_4.geometry}
            material={materials.glass}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.DoorComputerRoom5R_1.geometry}
            material={materials.wall}
          />
          <mesh
            geometry={nodes.DoorComputerRoom5R_2.geometry}
            material={materials.rack}
          />
          <mesh
            geometry={nodes.DoorComputerRoom5R_3.geometry}
            material={materials.alu}
          />
          <mesh
            geometry={nodes.DoorComputerRoom5R_4.geometry}
            material={materials.glass}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.DoorComputerRoom5L_1.geometry}
            material={materials.wall}
          />
          <mesh
            geometry={nodes.DoorComputerRoom5L_2.geometry}
            material={materials.rack}
          />
          <mesh
            geometry={nodes.DoorComputerRoom5L_3.geometry}
            material={materials.alu}
          />
          <mesh
            geometry={nodes.DoorComputerRoom5L_4.geometry}
            material={materials.glass}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.DoorComputerRoom3L_1.geometry}
            material={materials.wall}
          />
          <mesh
            geometry={nodes.DoorComputerRoom3L_2.geometry}
            material={materials.rack}
          />
          <mesh
            geometry={nodes.DoorComputerRoom3L_3.geometry}
            material={materials.alu}
          />
          <mesh
            geometry={nodes.DoorComputerRoom3L_4.geometry}
            material={materials.glass}
          />
        </group>
        <group>
          <mesh
            geometry={nodes.DoorComputerRoom3R_1.geometry}
            material={materials.wall}
          />
          <mesh
            geometry={nodes.DoorComputerRoom3R_2.geometry}
            material={materials.rack}
          />
          <mesh
            geometry={nodes.DoorComputerRoom3R_3.geometry}
            material={materials.alu}
          />
          <mesh
            geometry={nodes.DoorComputerRoom3R_4.geometry}
            material={materials.glass}
          />
        </group>
      </RigidBody>
      <RigidBody colliders="cuboid" type="fixed">
        {/* Chairs */}
      </RigidBody>
      <RigidBody colliders="hull" type="fixed" restitution={0} friction={0}>
        {/* Desks */}
      </RigidBody>
      <RigidBody
        type="fixed"
        colliders="cuboid"
        restitution={0}
        friction={1}
      >
        {/* Second Floor */}
        <mesh
          geometry={nodes.SecondFloor.geometry}
          material={materials.floor}
        />
      </RigidBody>
      {/* Top Second Floor */}
      {/* Whiteboards */}
    </group>
  );
};
export default EISCSecondFloor;

useGLTF.preload("/models/EISCSecondFloor.glb");
